# Generated by Django 2.1.7 on 2019-02-25 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(choices=[('Short Courses', (('Short Course 1', 'Short Course 1'), ('Short Course 1', 'Short Course 1'))), ('FET Certificate', (('Systems Development', 'Systems Development'), ('Advertising', 'Advertising'), ('Technical Support', 'Technical Support'))), ('NATIONAL Certificate', (('Advertising', 'Advertising'), ('Business Analysis', 'Business Analysis'), ('Systems Development', 'Systems Development'), ('Business Analysis Support Practises', 'Business Analysis Support Practises'), ('End User Computing', 'End User Computing'), ('System Support', 'System Support')))], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_for_academy_year', models.DateField()),
                ('highest_grade_passed', models.CharField(max_length=200)),
                ('name_of_high_school', models.CharField(max_length=200)),
                ('final_examination_date', models.DateField()),
                ('certified_identity_document', models.FileField(upload_to='document')),
                ('certified_metric_certificate', models.FileField(upload_to='document')),
                ('programe_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.ProgramType')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(help_text='Your last name', max_length=200)),
                ('full_names', models.CharField(help_text='Your first name(s)', max_length=200)),
                ('date_of_birth', models.DateTimeField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('citizenship', models.CharField(default='south africa', max_length=200)),
                ('identity_number', models.CharField(max_length=25)),
                ('passport_number', models.CharField(max_length=25)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(help_text='House No and Street Name', max_length=200)),
                ('Suburb', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=50)),
                ('name_and_surname', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=200)),
                ('cell_number', models.CharField(max_length=50)),
                ('work_number', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='qualification',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.Student'),
        ),
    ]
