# Generated by Django 2.1.7 on 2019-02-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='certified_identity_document',
            field=models.FileField(upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='certified_metric_certificate',
            field=models.FileField(upload_to='upload'),
        ),
    ]
